version: "3.2"

services:
  app:
    image: mahendrshinde/sample-app:v1
  
  lb:
    image: nginx:1.7.9
    # Mount my custom NGINX configuration in READ-ONLY MODE
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: 
      - app
    # Map NGINX port 80 to host port 8000
    # Enabling you to access Load balancer at URL:
    # localhost:8000
    ports: 
      - 8000:80