version: "3.2"

services:
  app:
    image: mahendrshinde/sample-app:v1
  
  lb:
    image: nginx:1.7.9
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: 
      - app
    ports: 
      - 8000:80